name: C++ Build CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        release: false # Используем предустановленный MSYS2 (самый быстрый и стабильный путь)
        update: false  # Не обновляем систему, чтобы не зависло
        install: mingw-w64-x86_64-gcc

    - name: Build Application
      shell: msys2 {0}
      run: |
        if [ "${{ matrix.build_type }}" == "Debug" ]; then
          g++ net_deleter.cpp -o NetDeleter_debug.exe -g -DDEBUG_MODE -DERROR_MODE -DINFO_MODE -static
        else
          g++ net_deleter.cpp -o NetDeleter.exe -O3 -DERROR_MODE -DINFO_MODE -static
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NetDeleter-${{ matrix.build_type }}
        path: "*.exe"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      with:
        files: |
          NetDeleter.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
