name: C++ Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Setup MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Build Application
      shell: cmd
      run: |
        if "${{ matrix.build_type }}"=="Debug" (
          g++ net_deleter.cpp -o NetDeleter_debug.exe -DDEBUG_MODE -DERROR_MODE -DINFO_MODE -static
        ) else (
          g++ net_deleter.cpp -o NetDeleter.exe -O3 -static
        )

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NetDeleter-${{ matrix.build_type }}
        path: "*.exe"
